// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlP1eeCA-BZoqv-jvpiCARI_UigR4yOso',
    appId: '1:586746644154:web:d3ce5f5f3201beb2672483',
    messagingSenderId: '586746644154',
    projectId: 'travel-planner-app-server',
    authDomain: 'travel-planner-app-server.firebaseapp.com',
    storageBucket: 'travel-planner-app-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRdQOWRwiIYDA_gjcAeDpmOB27SshoYw',
    appId: '1:586746644154:android:8881be776f1676e9672483',
    messagingSenderId: '586746644154',
    projectId: 'travel-planner-app-server',
    storageBucket: 'travel-planner-app-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNttL71mhHXme-Gn7roDeY1wvuq-ySk4',
    appId: '1:586746644154:ios:62d3bdb256b8ae31672483',
    messagingSenderId: '586746644154',
    projectId: 'travel-planner-app-server',
    storageBucket: 'travel-planner-app-server.appspot.com',
    iosBundleId: 'com.example.travelplannerapp',
  );

}